services:
  Contexts.Backoffice.Task.infra.BullMQ.BullTaskWorker:
    class: ../../../../../Contexts/Backoffice/Task/infra/BullMQ/BullTaskWorker
    arguments: [
      '@Contexts.Backoffice.Task.infra.BullMQ.BullConfig',
      'task-queue',
      '@Contexts.Backoffice.Task.application.TimeOut.TaskTimeOutProcessor'
    ]

  Contexts.Backoffice.Task.infra.BullMQ.TaskQueue:
    arguments: ['task-queue']
    factory:
      class: '@Contexts.Backoffice.Task.infra.BullMQ.BullConfig'
      method: 'createQueue'

  Contexts.Backoffice.Task.infra.BullMQ.TaskScheduler:
    class: ../../../../../Contexts/Backoffice/Task/infra/BullMQ/BullTaskScheduler
    arguments: ['@Contexts.Backoffice.Task.infra.BullMQ.TaskQueue']

  Contexts.Backoffice.Task.application.Create.TaskCreator:
    class: ../../../../../Contexts/Backoffice/Task/application/Create/TaskCreator
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository",
    "@Contexts.Backoffice.User.infra.persistence.UserRepository",
    "@Contexts.Backoffice.Task.infra.BullMQ.TaskScheduler",
    "@Contexts.Backoffice.Department.infra.persistence.DepartmentRepository"
  ]

  Contexts.Backoffice.Task.application.SearchAll.TaskSearcher:
    class: ../../../../../Contexts/Backoffice/Task/application/SearchAll/TaskSearcher
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository"
  ]

  Contexts.Backoffice.Task.application.Find.TaskFinder:
    class: ../../../../../Contexts/Backoffice/Task/domain/TaskFinder
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository"
  ]

  Contexts.Backoffice.Task.application.Update.TaskUpdator:
    class: ../../../../../Contexts/Backoffice/Task/application/Update/TaskUpdator
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository",
    "@Contexts.Backoffice.Task.infra.BullMQ.TaskScheduler",
    "@Contexts.Backoffice.Department.infra.persistence.DepartmentRepository"
    ]

  Contexts.Backoffice.Task.application.Delete.TaskDeleter:
    class: ../../../../../Contexts/Backoffice/Task/application/Delete/TaskDeleter
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository",
    "@Contexts.Backoffice.Task.infra.BullMQ.TaskScheduler"
  ]

  Contexts.Backoffice.Task.application.TimeOut.TaskTimeOutProcessor:
    class: ../../../../../Contexts/Backoffice/Task/application/TimeOut/TaskTimeOutProcessor
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository"
  ]

  Contexts.Backoffice.Task.application.ChangeStatus.TaskStatusChanger:
    class: ../../../../../Contexts/Backoffice/Task/application/ChangeStatus/TaskStatusChanger
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository",
    "@Contexts.Backoffice.Task.infra.BullMQ.TaskScheduler"
  ]

  Contexts.Backoffice.Task.application.UserKanban.UserKanbanGenerator:
    class: ../../../../../Contexts/Backoffice/Task/application/UserKanban/UserKanbanGenerator
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository"
  ]

  Contexts.Backoffice.Task.application.Overview.TaskOverviewer:
    class: ../../../../../Contexts/Backoffice/Task/application/Overview/TaskOverviewer
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository"
  ]

  Contexts.Backoffice.Task.application.SearchCriteria.TaskFilter:
    class: ../../../../../Contexts/Backoffice/Task/application/SearchCriteria/TaskFilter
    arguments: [
    "@Contexts.Backoffice.Task.infra.persistence.TaskRepository"
  ]

  