version: '1'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dimedical
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - /app/node_modules/
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
volumes:
  db:
    driver: local
