version: '1'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dimedical
    ports:
      - "8080:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./di-medical-managment
    depends_on:
      - db
    volumes:
      - /server/node_modules/
      - ./di-medical-managment:/server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./di-medical-client
    depends_on:
      - api
    volumes:
      - /client/node_modules/
      - ./di-medical-client:/client
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - "9000:9000"
volumes:
  db:
