version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dimedical
    ports:
      - "8080:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
