services:
  Contexts.Backoffice.Attendance.application.SearchAll.IssueSearcher:
    class: ../../../../../Contexts/Backoffice/Attendance/application/SearchAll/IssueSearcher
    arguments: [
    "@Contexts.Backoffice.Attendance.infra.persistence.AttendanceRepository",
    "@Contexts.Backoffice.User.infra.persistence.UserRepository"
    ]

  Contexts.Backoffice.Attendance.application.CreateIssue.IssueCreator:
    class: ../../../../../Contexts/Backoffice/Attendance/application/CreateIssue/IssueCreator
    arguments: [
    "@Contexts.Backoffice.Attendance.infra.persistence.AttendanceRepository"
    ]
