services:
  Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository:
    class: ../../../../Contexts/Warehouse/Sucursal/infra/persistence/FakeSucursalRepository
  
  Contexts.Warehouse.Sucursal.application.Create.SucursalCreator:
    class: ../../../../Contexts/Warehouse/Sucursal/application/Create/SucursalCreator
    arguments: ["@Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository"]
  
  Contexts.Warehouse.Sucursal.application.Update.SucursalUpdator:
    class: ../../../../Contexts/Warehouse/Sucursal/application/Update/SucursalUpdator
    arguments: ["@Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository"]
  
  Apps.warehouse.backend.controllers.SucursalCreateController:
    class: ../controllers/SucursalCreateController
    arguments: ["@Contexts.Warehouse.Sucursal.application.Create.SucursalCreator"]
  
  Apps.warehouse.backend.controllers.SucursalUpdateController:
    class: ../controllers/SucursalUpdateController
    arguments: ["@Contexts.Warehouse.Sucursal.application.Update.SucursalUpdator"]

  Contexts.Warehouse.User.infra.persistence.UserRepository:
    class: ../../../../Contexts/Warehouse/User/infra/persistence/FakeUserRepository
  
  Contexts.Warehouse.User.application.Create.UserCreator:
    class: ../../../../Contexts/Warehouse/User/application/Create/UserCreator
    arguments: [
    "@Contexts.Warehouse.User.infra.persistence.UserRepository",
    "@Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository"
    ]
  
  Apps.warehouse.backend.controllers.UserCreateController:
    class: ../controllers/UserCreateController
    arguments: [
      "@Contexts.Warehouse.User.application.Create.UserCreator"
    ]

  Contexts.Warehouse.Truck.infra.persistence.TruckRepository:
    class: ../../../../Contexts/Warehouse/Truck/infra/persistence/FakeTruckRepository
  
  Contexts.Warehouse.Truck.application.Create.TruckCreator:
    class: ../../../../Contexts/Warehouse/Truck/application/Create/TruckCreator
    arguments: [
    "@Contexts.Warehouse.Truck.infra.persistence.TruckRepository",
    ]
  
  Contexts.Warehouse.Truck.application.Update.TruckUpdator:
    class: ../../../../Contexts/Warehouse/Truck/application/Update/TruckUpdator
    arguments: [
    "@Contexts.Warehouse.Truck.infra.persistence.TruckRepository",
  ]
  
  Contexts.Warehouse.Truck.application.AddIncident.TruckIncidentAdder:
    class: ../../../../Contexts/Warehouse/Truck/application/AddIncident/TruckIncidentAdder
    arguments: [
    "@Contexts.Warehouse.Truck.infra.persistence.TruckRepository",
    ]

  Apps.warehouse.backend.controllers.TruckCreateController:
    class: ../controllers/truck/TruckCreateController
    arguments: [
      "@Contexts.Warehouse.Truck.application.Create.TruckCreator"
    ]
  
  Apps.warehouse.backend.controllers.TruckUpdateController:
    class: ../controllers/truck/TruckUpdateController
    arguments: [
      "@Contexts.Warehouse.Truck.application.Update.TruckUpdator"
    ]

  Apps.warehouse.backend.controllers.IncidentCreateController:
    class: ../controllers/truck/IncidentCreateController
    arguments: [
      "@Contexts.Warehouse.Truck.application.AddIncident.TruckIncidentAdder"
    ]

  Contexts.Warehouse.Client.infra.persistence.ClientRepository:
    class: ../../../../Contexts/Warehouse/Client/infra/persistence/FakeClientRepository

  Contexts.Warehouse.Client.application.Create.ClientCreator:
    class: ../../../../Contexts/Warehouse/Client/application/Create/ClientCreator
    arguments: [
    "@Contexts.Warehouse.Client.infra.persistence.ClientRepository",
    ]

  Apps.warehouse.backend.controllers.ClientCreateController:
    class: ../controllers/client/ClientCreateController
    arguments: [
      "@Contexts.Warehouse.Client.application.Create.ClientCreator"
    ]
