services:
  Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository:
    class: ../../../../Contexts/Warehouse/Sucursal/infra/persistence/FakeSucursalRepository
  
  Contexts.Warehouse.Sucursal.application.Create.SucursalCreator:
    class: ../../../../Contexts/Warehouse/Sucursal/application/Create/SucursalCreator
    arguments: ["@Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository"]
  Contexts.Warehouse.Sucursal.application.Update.SucursalUpdator:
    class: ../../../../Contexts/Warehouse/Sucursal/application/Update/SucursalUpdator
    arguments: ["@Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository"]
 
  Apps.warehouse.backend.controllers.SucursalCreateController:
    class: ../controllers/SucursalCreateController
    arguments: ["@Contexts.Warehouse.Sucursal.application.Create.SucursalCreator"]
  Apps.warehouse.backend.controllers.SucursalUpdateController:
    class: ../controllers/SucursalUpdateController
    arguments: ["@Contexts.Warehouse.Sucursal.application.Update.SucursalUpdator"]
