services:
  Contexts.Backoffice.Product.application.Find.SearchAllTags.TagSearcher:
    class: ../../../../../Contexts/Backoffice/Products/application/SearchAllTags/TagSearcher
    arguments: [
    "@Contexts.Backoffice.Analytics.infra.persistence.ProductRepository"
  ]

  Contexts.Backoffice.Product.application.CreateTag.TagCreator:
    class: ../../../../../Contexts/Backoffice/Products/application/CreateTag/TagCreator
    arguments: [
    "@Contexts.Backoffice.Analytics.infra.persistence.ProductRepository"
  ]

  Contexts.Backoffice.Product.application.DeleteTag.TagDeletor:
    class: ../../../../../Contexts/Backoffice/Products/application/DeleteTag/TagDeletor
    arguments: [
    "@Contexts.Backoffice.Analytics.infra.persistence.ProductRepository"
  ]

  Contexts.Backoffice.Product.application.SearchAllBrands.BrandSearcher:
    class: ../../../../../Contexts/Backoffice/Products/application/SearchAllBrands/BrandSearcher
    arguments: [
    "@Contexts.Backoffice.Analytics.infra.persistence.ProductRepository"
  ]

  Contexts.Backoffice.Product.application.CreateBrand.BrandCreator:
    class: ../../../../../Contexts/Backoffice/Products/application/CreateBrand/BrandCreator
    arguments: [
    "@Contexts.Backoffice.Analytics.infra.persistence.ProductRepository"
  ]
