services:
  Contexts.Backoffice.Sucursal.infra.persistence.SucursalRepository:
    class: ../../../../Contexts/Backoffice/Sucursal/infra/persistence/FakeSucursalRepository
  
  Contexts.Backoffice.Sucursal.application.Create.SucursalCreator:
    class: ../../../../Contexts/Backoffice/Sucursal/application/Create/SucursalCreator
    arguments: ["@Contexts.Backoffice.Sucursal.infra.persistence.SucursalRepository"]
  
  Contexts.Backoffice.Sucursal.application.Update.SucursalUpdator:
    class: ../../../../Contexts/Backoffice/Sucursal/application/Update/SucursalUpdator
    arguments: ["@Contexts.Backoffice.Sucursal.infra.persistence.SucursalRepository"]
  
  Apps.Backoffice.backend.controllers.SucursalCreateController:
    class: ../controllers/SucursalCreateController
    arguments: ["@Contexts.Backoffice.Sucursal.application.Create.SucursalCreator"]
  
  Apps.Backoffice.backend.controllers.SucursalUpdateController:
    class: ../controllers/SucursalUpdateController
    arguments: ["@Contexts.Backoffice.Sucursal.application.Update.SucursalUpdator"]

  Contexts.Backoffice.User.infra.persistence.UserRepository:
    class: ../../../../Contexts/Backoffice/User/infra/persistence/FakeUserRepository
  
  Contexts.Backoffice.User.application.Create.UserCreator:
    class: ../../../../Contexts/Backoffice/User/application/Create/UserCreator
    arguments: [
    "@Contexts.Backoffice.User.infra.persistence.UserRepository",
    "@Contexts.Backoffice.Sucursal.infra.persistence.SucursalRepository"
    ]
  
  Apps.Backoffice.backend.controllers.UserCreateController:
    class: ../controllers/UserCreateController
    arguments: [
      "@Contexts.Backoffice.User.application.Create.UserCreator"
    ]

  Contexts.Backoffice.Truck.infra.persistence.TruckRepository:
    class: ../../../../Contexts/Backoffice/Truck/infra/persistence/FakeTruckRepository
  
  Contexts.Backoffice.Truck.application.Create.TruckCreator:
    class: ../../../../Contexts/Backoffice/Truck/application/Create/TruckCreator
    arguments: [
    "@Contexts.Backoffice.Truck.infra.persistence.TruckRepository",
    ]
  
  Contexts.Backoffice.Truck.application.Update.TruckUpdator:
    class: ../../../../Contexts/Backoffice/Truck/application/Update/TruckUpdator
    arguments: [
    "@Contexts.Backoffice.Truck.infra.persistence.TruckRepository",
  ]
  
  Contexts.Backoffice.Truck.application.AddIncident.TruckIncidentAdder:
    class: ../../../../Contexts/Backoffice/Truck/application/AddIncident/TruckIncidentAdder
    arguments: [
    "@Contexts.Backoffice.Truck.infra.persistence.TruckRepository",
    ]

  Apps.Backoffice.backend.controllers.TruckCreateController:
    class: ../controllers/truck/TruckCreateController
    arguments: [
      "@Contexts.Backoffice.Truck.application.Create.TruckCreator"
    ]
  
  Apps.Backoffice.backend.controllers.TruckUpdateController:
    class: ../controllers/truck/TruckUpdateController
    arguments: [
      "@Contexts.Backoffice.Truck.application.Update.TruckUpdator"
    ]

  Apps.Backoffice.backend.controllers.IncidentCreateController:
    class: ../controllers/truck/IncidentCreateController
    arguments: [
      "@Contexts.Backoffice.Truck.application.AddIncident.TruckIncidentAdder"
    ]

  Contexts.Backoffice.Client.infra.persistence.ClientRepository:
    class: ../../../../Contexts/Backoffice/Client/infra/persistence/FakeClientRepository

  Contexts.Backoffice.Client.application.Create.ClientCreator:
    class: ../../../../Contexts/Backoffice/Client/application/Create/ClientCreator
    arguments: [
    "@Contexts.Backoffice.Client.infra.persistence.ClientRepository",
    ]
  
  Contexts.Backoffice.Client.application.Update.ClientUpdator:
    class: ../../../../Contexts/Backoffice/Client/application/Update/ClientUpdator
    arguments: [
    "@Contexts.Backoffice.Client.infra.persistence.ClientRepository"
    ]

  Apps.Backoffice.backend.controllers.ClientCreateController:
    class: ../controllers/client/ClientCreateController
    arguments: [
      "@Contexts.Backoffice.Client.application.Create.ClientCreator"
    ]

  Apps.Backoffice.backend.controllers.ClientUpdateController:
    class: ../controllers/client/ClientUpdateController
    arguments: [
      "@Contexts.Backoffice.Client.application.Update.ClientUpdator"
    ]

  Contexts.Backoffice.Survey.infra.persistence.SurveyRepository:
    class: ../../../../Contexts/Backoffice/Survey/infra/persistence/FakeSurveyRepository

  Contexts.Backoffice.Survey.application.Create.SurveyCreator:
    class: ../../../../Contexts/Backoffice/Survey/application/Create/SurveyCreator
    arguments: [
    "@Contexts.Backoffice.Survey.infra.persistence.SurveyRepository",
    ]

  Contexts.Backoffice.Survey.application.Create.SurveyAnswerer:
    class: ../../../../Contexts/Backoffice/Survey/application/Answer/SurveyAnswerer
    arguments: [
    "@Contexts.Backoffice.Survey.infra.persistence.SurveyRepository",
    ]

  Apps.Backoffice.backend.controllers.SurveyCreateController:
    class: ../controllers/survey/SurveyCreateController
    arguments: [
      "@Contexts.Backoffice.Survey.application.Create.SurveyCreator"
    ]

  Apps.Backoffice.backend.controllers.SurveyAnswerController:
    class: ../controllers/survey/SurveyAnswerController
    arguments: [
      "@Contexts.Backoffice.Survey.application.Create.SurveyAnswerer"
    ]
