
imports:
  - { resource: ./repositories/application.yaml }
  - { resource: ./modules/application.yaml }
  - { resource: ./sucursal/application.yaml }
  - { resource: ./user/application.yaml }
  - { resource: ./truck/application.yaml }
  - { resource: ./client/application.yaml }
  - { resource: ./surveys/application.yaml }
  - { resource: ./task/application.yaml }
  - { resource: ./itinerary/application.yaml }
  - { resource: ./permit/application.yaml }
  - { resource: ./departments/application.yaml }
  - { resource: ./attendance/application.yaml }
  - { resource: ./analytics/application.yaml }
  - { resource: ./products/application.yaml }
  - { resource: ./controllers/application.yaml }
