services:
  Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository:
    class: ../../../../Contexts/Warehouse/Sucursal/infra/persistence/PrismaSucursalRepository
  Contexts.Warehouse.Sucursal.application.Create.SucursalCreator:
    class: ../../../../Contexts/Warehouse/Sucursal/application/Create/SucursalCreator
    arguments: ["@Contexts.Warehouse.Sucursal.infra.persistence.SucursalRepository"]
  Apps.warehouse.backend.controllers.SucursalCreateController:
    class: ../controllers/SucursalCreateController
    arguments: ["@Contexts.Warehouse.Sucursal.application.Create.SucursalCreator"]
